"""add chunk_configs and parent_content

Revision ID: 53eacc65c596
Revises: eebf3ca13bb4
Create Date: 2026-06-25 08:42:41.768412

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '53eacc65c596'
down_revision: str | None = 'eebf3ca13bb4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunk_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=64), nullable=False),
    sa.Column('strategy', sa.String(length=32), nullable=False),
    sa.Column('chunk_size', sa.Integer(), nullable=False),
    sa.Column('overlap', sa.Integer(), nullable=False),
    sa.Column('parent_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_type')
    )
    op.add_column('document_chunks', sa.Column('parent_content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'parent_content')
    op.drop_table('chunk_configs')
    # ### end Alembic commands ###
