"""add unique constraint on documents version

Revision ID: b68214f96ed9
Revises: 4c9087626ef9
Create Date: 2026-06-24 19:12:05.737916

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'b68214f96ed9'
down_revision: str | None = '4c9087626ef9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_documents_name_type_version', 'documents', ['name', 'doc_type', 'version'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_documents_name_type_version', 'documents', type_='unique')
    # ### end Alembic commands ###
