"""add schema_docs (semantic layer)

Revision ID: d18b09984b02
Revises: d150aa3129f4
Create Date: 2026-06-25 18:45:13.255311

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import pgvector  # 向量列类型 pgvector.sqlalchemy.vector.VECTOR 要用到，autogenerate 没自动加，手动补
from sqlalchemy.dialects import postgresql

revision: str = 'd18b09984b02'
down_revision: str | None = 'd150aa3129f4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schema_docs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('object_name', sa.String(length=256), nullable=False),
    sa.Column('desc', sa.Text(), nullable=False),
    sa.Column('grain', sa.Text(), nullable=True),
    sa.Column('columns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('relations', sa.Text(), nullable=True),
    sa.Column('samples', sa.Text(), nullable=True),
    sa.Column('aliases', sa.Text(), nullable=True),
    sa.Column('required_filter', sa.String(length=128), nullable=True),
    sa.Column('default_window', sa.String(length=64), nullable=True),
    sa.Column('max_window', sa.String(length=64), nullable=True),
    sa.Column('isolation', sa.String(length=32), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_name')
    )
    op.create_index('ix_schema_docs_embedding_hnsw', 'schema_docs', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_schema_docs_embedding_hnsw', table_name='schema_docs', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('schema_docs')
    # ### end Alembic commands ###
