"""add tsvector column and gin index for chinese fts

Revision ID: eebf3ca13bb4
Revises: b68214f96ed9
Create Date: 2026-06-25 08:20:14.896149

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'eebf3ca13bb4'
down_revision: str | None = 'b68214f96ed9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('ts', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', coalesce(content_tokens, ''))", persisted=True), nullable=True))
    op.create_index('ix_chunks_ts', 'document_chunks', ['ts'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chunks_ts', table_name='document_chunks', postgresql_using='gin')
    op.drop_column('document_chunks', 'ts')
    # ### end Alembic commands ###
